[package]
name = "nosql-navigate"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
mongodb = "2.5.0"
serde_json = "1.0.96"
serde = { version = "1.0.162", features = ["derive"] }
thiserror = "1.0"
futures = "0.3.28"
chrono = "0.4.24"
uuid = { version = "1.3.0", features = ["v4"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
tauri = { version = "1.3.0", features = ["dialog-open", "dialog-save", "shell-open"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
